version: '3.8'

services:
  process-exporter:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9113:9113"
    restart: unless-stopped
    pid: host
    privileged: true
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro